### ISSUE TITLE
Cannot build configmaps

### ISSUE THREAD

**Issue by AlexanderFabisch** [rock-simulation/configmaps#9]
During aup

    ...
    installing OS packages: libjsoncpp-dev
    Command finished successfully at 2017-08-14 11:37:09 +0200

seems to be successful, however, I get the following error:

```
$ make
[ 16%] Building CXX object CMakeFiles/configmaps.dir/src/ConfigMap.cpp.o
In file included from /home/dfki.uni-bremen.de/afabisch/tmp/envire/tools/configmaps/src/ConfigMap.cpp:7:0:
/home/dfki.uni-bremen.de/afabisch/tmp/envire/tools/configmaps/src/ConfigAtom.hpp:33:23: fatal error: json/json.h: No such file or directory
compilation terminated.
CMakeFiles/configmaps.dir/build.make:62: recipe for target 'CMakeFiles/configmaps.dir/src/ConfigMap.cpp.o' failed
make[2]: *** [CMakeFiles/configmaps.dir/src/ConfigMap.cpp.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/configmaps.dir/all' failed
make[1]: *** [CMakeFiles/configmaps.dir/all] Error 2
Makefile:116: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by malter** [comment]
Hey,

du könntest mal versuchen den build Ordner zu löschen und dann nochmal bauen.

Gruß,
  Malte

_____________________________
vom Handy gesendet

Malte Langosz

Heinrich-Goebel-Str. 29
28357 Bremen



_____________________________
vom Handy gesendet

Malte Langosz

Heinrich-Goebel-Str. 29
28357 Bremen

**Comment by AlexanderFabisch** [comment]
OK, ich verstehe nicht warum, aber das hat funktioniert. Danke!

**Comment by malter** [comment]
Normalerweise konfiguriert cmake neu wenn die CMakeLists.txt geändert wird. Aber es gibt Fälle in denen das nicht klappt und neue Abhängigkeiten nicht korrekt ergänzt werden. Dann muss man den build Ordner (cmake cache) löschen.
Ich meine wenn man per pkg_check_modules mehrere Abhängigkeiten lädt und die Liste sich ändert schlägt das neu konfigurieren fehl.
